/**
 * The generated Worker entry. It's a plain ESM file, not magic: it imports
 * the CLI-generated pure-data config module (relative path) plus
 * resolveConfig/snapshotOf/createApp from the "edgecms" umbrella package —
 * never from @edgecms/config or @edgecms/runtime directly, since a project
 * only ever declares "edgecms" as a dependency, and package managers with
 * strict, non-hoisted resolution (pnpm workspaces in particular) won't
 * resolve a bare import of a transitive dependency that isn't re-exported
 * through something the project actually depends on (see
 * packages/edgecms/src/index.ts). Config changes always require a
 * rebuild/redeploy since the Worker can't read cms.config.ts off disk at
 * request time.
 */
export function generateEntrySource(
  configImportPath: string,
  adapter = "d1",
  pluginsImportPath?: string,
): string {
  // Only Postgres/MySQL projects import an external adapter factory (from the
  // `edgecms/postgres`|`/mysql` subpaths). A D1 project imports nothing extra,
  // so its bundle never references the external drivers.
  const external =
    adapter === "postgres"
      ? { subpath: "edgecms/postgres", symbol: "postgresAdapter" }
      : adapter === "mysql"
        ? { subpath: "edgecms/mysql", symbol: "mysqlAdapter" }
        : null;

  const externalImport = external ? `import { ${external.symbol} } from ${JSON.stringify(external.subpath)};\n` : "";
  const pluginsImport = pluginsImportPath ? `import plugins from ${JSON.stringify(pluginsImportPath)};\n` : "";
  // Assemble createApp options only when there's something to pass.
  const optionParts = [
    ...(external ? [`databaseAdapter: ${external.symbol}`] : []),
    ...(pluginsImportPath ? [`plugins`] : []),
  ];
  const createAppCall = optionParts.length
    ? `createApp(resolved, snapshot, { ${optionParts.join(", ")} })`
    : `createApp(resolved, snapshot)`;

  return `// AUTO-GENERATED by edgecms — do not edit; regenerated on every \`edgecms dev\`/\`deploy\`.
import userConfig from ${JSON.stringify(configImportPath)};
import { resolveConfig, snapshotOf, createApp } from "edgecms";
${externalImport}${pluginsImport}
const resolved = resolveConfig(userConfig);
const snapshot = snapshotOf(resolved);
const app = ${createAppCall};

export default {
  fetch: (request, env, ctx) => app.fetch(request, env, ctx),
};
`;
}
